### ISSUE TITLE
Wrong quarter dates

### ISSUE THREAD

**Issue by Frosty002** [ShinyHobo/shinyhobo.github.io#73]
Noticed that the months of the quarters where wrong and are ahead by one month. Tested on Opera GX and Microsoft Edge and still have the same issues. 
![Opera Snapshot_2023-05-30_213056_shinytracker app](https://github.com/ShinyHobo/shinyhobo.github.io/assets/135067979/f94a10ac-cfe2-4cb8-9e11-2979b1cba1aa)

**Comment by ShinyHobo** [comment]
I have tested it in both the latest builds of Opera GX and Edge without the ability to replicate. Are you running any extensions that might be interfering with the javascript? What screen resolution are you using and on what OS?

If you open the Inspect Element console, what messages are present?

**Comment by Frosty002** [comment]
ps://gc.zgo.at/count.js net::ERR_BLOCKED_BY_ADBLOCKER
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

I get these messages

**Comment by ShinyHobo** [comment]
Possible fix implemented
